remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Git 4 Goicke
description: Git Anleitung für Goicke
domain: git.fullme.sh
url: https://git.fullme.sh
github_username: feicht